menu:
  Home: /
  Archives: /archives

# gitment
gitment: true
gitment_owner: RealCaCl2
gitment_repo: website
gitment_client_id: 6d322105aa88fd54e564
gitment_client_secret: 215807cec5bb2b6b99b823a95792a1a9feb3f8cb

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# utterances comment
utterances: false
utterances_repo:

# livere city comment
livere: false
livere_data_uid:

# giscus comment
giscus: false
data_repo: 
data_repo_id: 
data_category: 
data_category_id: 
data_mapping: pathname
#data_term: 
data_strict: 0
data_reactions_enabled: 0
data_emit_metadata: 0
data_input_position: top
data_loading: 
data_lang: en

# google analytics
googleTrackId:

# baidu analytics
baiduTrackId:

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true
